apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vote-ingress
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
spec:
  rules:
  - http:
      paths:
      - pathType: Prefix
        path: /production
        backend:
          service:
            name: votecluster
            port:
              number: 80
      - pathType: Prefix
        path: /canary
        backend:
          service:
            name: votecanarycluster
            port:
              number: 80
